import type { LessonVideoKey } from "@/lib/lessonVideos";

export const whatItIsLesson = {
  id: 'whatItIs',
  slug: '/learn/what-it-is',
  eyebrow: 'Lesson 1 of 4',
  title: 'It generates. It does not retrieve.',
  next: '/learn/what-it-can-do',
  nextLabel: 'Next — When the draft is useful',
  videoKey: 'whatItIs' as LessonVideoKey,
  body: '**Retrieve** means there is already a source. A map, a schedule, a phone number, a page. The job is to find it.\n\n**Generate** means there is no single page. The machine predicts a plausible next stretch of language from patterns in a huge pile of writing, pictures, and code.\n\nThe same chat window will do both. It will not label which job it is doing. You have to notice.\n\n## What it is not\n\n- A person who understands you\n- A librarian who checked a footnote\n- A second brain that knows your kitchen\n- “The internet,” compressed\n\n## What it is\n\nSoftware that is very good at continuing a pattern. Useful when you need a draft. Dangerous when you needed a fact and forgot to check.\n\nIf you remember one line: **search retrieves. This generates.**\n\n<details>\n<summary>Deeper aside — for people who like the lineage</summary>\n\n“Artificial intelligence” as a research idea is old. People have been trying to make machines that infer, not just follow a typed recipe, since the mainframe era.\n\nWhat is in the chat box now is a specific recent instrument: a large model trained to guess the next word (or image patch, or line of code) from context. That is why it can draft a letter, and also why it can sound sure when it is wrong. Old idea, new instrument. You can skip this and still use the instrument well.\n</details>\n\n## Worked example — same city, two jobs\n\n**FIND:** “Is Richmond, Virginia in the Eastern Time Zone?”  \nA stable fact. If a chat answers, you can still confirm in two seconds. The answer is not the point. The *kind of question* is.\n\n**MAKE:** “Explain Eastern Time to my cousin who keeps missing our calls from another country. No jargon. Four sentences. Warm.”  \nThere is no official cousin-paragraph in a database. The model will invent a clear one. You read it. You keep the tone or you don’t.\n\nIf you run a FIND and trust last year’s post-office hours, you miss the window.  \nIf you run a MAKE and skip reading, you mail a letter that does not sound like you.\n\n## The mix-up\n\nPeople ask FIND questions in the tone of MAKE (“just tell me”) and MAKE questions in the tone of FIND (“what’s the official way”). This lesson is only: name the job before you believe the answer.',
  exercise: 'In Notes, write two asks you might actually make this month.\n\n- Label one **FIND** (a fact that should already exist).\n- Label one **MAKE** (a draft that should not exist until you write it).\n\nDo not run them yet.',
} as const;
