import type { LessonVideoKey } from "@/lib/lessonVideos";

export const whatItCanDoLesson = {
  id: 'whatItCanDo',
  slug: '/learn/what-it-can-do',
  eyebrow: 'Lesson 2 of 4',
  title: 'When the draft is useful',
  next: '/learn/how-and-why',
  nextLabel: 'Next — Give it a brief',
  videoKey: 'whatItCanDo' as LessonVideoKey,
  body: 'It helps when three things are true at once:\n\n1. You need language, options, or an explanation — not a hidden fact.\n2. You can recognize a bad answer.\n3. You will read it before it leaves the room.\n\n## Yes — this is the job\n\n**Messy notes → a list.** You dumped six lines about a birthday dinner. You want a shopping list and an order of events. You know whether you already have napkins. The model does not.\n\n**A letter you dread.** Landlord, school, insurance, a thank-you you keep putting off. You know the facts. You are stuck on tone.\n\n**Explain this like I’m not in that world.** A bill, a school email, a repair quote. You want translation, not a verdict.\n\n**Three versions.** Same message, three temperatures: warmer, shorter, more direct. You pick. That is taste, not automation.\n\n## No — close it and look it up\n\nHours, prices, doses, laws, whether a person is dead, what your bank did. If being wrong is expensive, do not trust this as the last word. You may still ask it to *explain* a document you already have.\n\n“Should I.” Should you take the job, sell the car, forgive them. It can list questions. It cannot stand in your life.\n\nFinished work you do not intend to touch. Accepting the first poem, logo, or plan is how the internet fills with slop. The skill here is the opposite.\n\n## Depends\n\n**News.** Good for: “Explain what this article is saying.” Bad for: “Tell me what happened” with no source. It will build a smooth story from a blur.\n\n**Health and money.** Good for: “This letter uses words I don’t know. Translate.” Bad for: “What do I have and what do I take?” That is not this campus, and not this tool’s job.\n\n<details>\n<summary>Deeper aside</summary>\n\nThe model has no private window into your kitchen, your job, or tomorrow. It has patterns. Your advantage is taste, stakes, and the ability to say “that is not my life.” Outsourcing judgment is how fancy search turns into expensive confusion.\n</details>\n\n## Worked example — one pile of notes\n\nYou type:\n\n```\nsat? uncle 70. he hates surprises but likes ham. sister bringing a cake maybe.\nhouse is a mess. budget 80. two kids coming. i work till 4.\n```\n\nA useful draft:\n\n- Saturday after 4\n- Ham-centered, not a surprise party\n- Cake: confirm sister\n- Budget $80\n- Clean the table, not the whole house\n- Kids: one simple activity\n\nA useless draft:\n\n- “Host an unforgettable luxury experience”\n- Recipes with ingredients you did not mention\n- A confident surprise brunch at 11\n\nYou can judge this without being a programmer because it is *your* uncle.\n\n## The test\n\nCan I judge this output without trusting it?\n\nIf yes, the tool is working for you.  \nIf no, you asked the wrong kind of question — or you are still in fancy-Google mode, only faster.',
  exercise: 'Pick one real pile from your life (notes, a dreaded email, a confusing paragraph).\n\nIn Notes write: **Job / Who it’s for / What I will use to judge the reply.**\n\nDo not generate yet. Judging criteria first.',
} as const;
